language: python
python:
- 3.6
- 3.7
- 3.8
install:
- pip install tox-travis
- pip install coveralls
deploy:
  provider: pypi
  user: dbarroso
  password:
    secure: d9XnLqr0mmLiMONfoiSqShwQ761pD3THIwsEtllm1/1KknoFyOtyqYOfPvUIvy2wg7JGDYyRCfyj1j3SiYz1whmmtAmtOZYYB14wk3eftNBVHDERc1ROOVO2u3ahL6WwdZBhxjpuz6lXX0sSJtDxY2IBFGDy2cj2VzWyuiWKoS2YrQoLTLBt/FWPbHvVIIeUkQ1wZnZ/G0H45ZAntd9v9BCFkjKc2wEagPYv5Li+54Tet8nFiNFC/m+UBbcgtITFp5xNz0nbjMDTxKwIEgRNqXig/P/OOeh3aNtjPZtwLdeuJw/p4QBZ+eCnqD9paGcOdkCpK6b4i+8RV8n3/Dpz3qbyYBxpMqAn+JnOpVpWWnoARI3Kc+hHMpuT9fPLt+J5iqU/YZQhDRavmrggYWlnqWk67udFxDBec6BidQuZfksVhdT6CcD5cATRDrV0m7CchAQa0RDJ9NRUFu3L6h3vP5F49xzFPa87fG1s9l/Qccby5/rR3cryyHcnxsw1F1kPD1cpWbHwmkPnWYAqzYIso8rhJ8XjNj4Cw5/S4E1ri4e7fKRmYKYgB7Eq1QkefODAoDu6LBOkf2JtGOrSEa+bwLx2nnoGWfs6KkkRKzJNuNwBVYQYhfSRXLsXzWwfpYwqCuuEt/p4scgkqLtm5cGqZ5EG15g52N9gnQzpK8MK+uw=
  on:
    tags: true
    branch: master
script:
- tox

after_success:
- coveralls
- if [ $TRAVIS_TAG ]; then curl -X POST https://readthedocs.org/build/napalm; fi
